using Rido.BFLite.Core.Schema;
using System.Text.RegularExpressions;

namespace Rido.BFLite.Core;

/// <summary>
/// Exception thrown when there's an error in streaming operations
/// </summary>
public class StreamingException : Exception
{
    public StreamingException(string message) : base(message) { }
    public StreamingException(string message, Exception innerException) : base(message, innerException) { }
}

/// <summary>
/// A helper class for streaming responses to the client.
/// This class is used to send a series of updates to the client in a single response. The expected
/// sequence of calls is:
/// 
/// `QueueInformativeUpdate()`, `QueueTextChunk()`, `QueueTextChunk()`, ..., `EndStream()`.
///
/// Once `EndStream()` is called, the stream is considered ended and no further updates can be sent.
/// </summary>
public class StreamingResponse
{
    private readonly BotApplication _botApplication;
    private readonly Activity _incomingActivity;
    private int _nextSequence = 1;
    private bool _ended = false;

    // Queue for outgoing activities
    private List<Func<Activity>> _queue = new();
    private Task? _queueSync;
    private bool _chunkQueued = false;

    /// <summary>
    /// Fluent interface for accessing the attachments.
    /// </summary>
    public List<Attachment>? Attachments { get; set; } = new();

    /// <summary>
    /// Sets the Feedback Loop in Teams that allows a user to give thumbs up or down to a response.
    /// Defaults to false.
    /// </summary>
    public bool? EnableFeedbackLoop { get; set; } = false;

    /// <summary>
    /// Represents the type of feedback loop. Set to "default" by default. It can be set to one of "default" or "custom".
    /// </summary>
    public string FeedbackLoopType { get; set; } = "default";

    /// <summary>
    /// Sets the "Generated by AI" label in Teams.
    /// Defaults to false.
    /// </summary>
    public bool? EnableGeneratedByAILabel { get; set; } = false;

    /// <summary>
    /// The citations for the response.
    /// </summary>
    public List<ClientCitation>? Citations { get; set; } = new();

    /// <summary>
    /// Gets the stream ID of the current response.
    /// Assigned after the initial update is sent.
    /// </summary>
    public string? StreamId { get; private set; }

    /// <summary>
    /// Fluent interface for accessing the message.
    /// </summary>
    public string Message { get; private set; } = "";

    /// <summary>
    /// Delay between streaming updates in milliseconds.
    /// Default is 1500ms (1.5 seconds) to prevent overwhelming the Bot Framework service.
    /// This follows the Microsoft Teams SDK implementation pattern.
    /// </summary>
    public int StreamingDelayMs { get; set; } = 1500;

    /// <summary>
    /// Gets the number of updates sent for the stream.
    /// </summary>
    /// <returns>Number of updates sent so far.</returns>
    public int UpdatesSent() => this._nextSequence - 1;

    /// <summary>
    /// Creates a new instance of the <see cref="StreamingResponse"/> class.
    /// </summary>
    /// <param name="botApplication">The bot application instance.</param>
    /// <param name="incomingActivity">The incoming activity that triggered this response.</param>
    public StreamingResponse(BotApplication botApplication, Activity incomingActivity)
    {
        _botApplication = botApplication;
        _incomingActivity = incomingActivity;
    }

    /// <summary>
    /// Waits for the outgoing activity queue to be empty.
    /// </summary>
    /// <returns></returns>
    public Task WaitForQueue()
    {
        return this._queueSync != null ? this._queueSync : Task.CompletedTask;
    }

    /// <summary>
    /// Set citations for the response.
    /// </summary>
    /// <param name="citations">The citations to add.</param>
    public void SetCitations(IList<Citation> citations)
    {
        if (citations != null && citations.Count > 0)
        {
            int currPos = 0;
            foreach (Citation citation in citations)
            {
                string abs = Snippet(citation.Content, 480);

                this.Citations!.Add(new ClientCitation()
                {
                    Position = currPos + 1,
                    Appearance = new ClientCitationAppearance()
                    {
                        Name = citation.Title,
                        Abstract = abs,
                        Url = citation.Url
                    }
                });
                currPos++;
            }
        }
    }

    /// <summary>
    /// Queues an informative update to be sent to the client.
    /// </summary>
    /// <param name="text">Text of the update to send.</param>
    /// <exception cref="StreamingException">Throws if the stream has already ended.</exception>
    public void QueueInformativeUpdate(string text)
    {
        if (this._ended)
        {
            throw new StreamingException("The stream has already ended.");
        }

        QueueActivity(() => CreateReplyActivity("typing", text, new StreamingChannelData
        {
            StreamType = Schema.StreamType.Informative,
            StreamSequence = this._nextSequence++,
        }));
    }

    /// <summary>
    /// Queues a chunk of partial message text to be sent to the client.
    /// </summary>
    /// <param name="text">Partial text of the message to send.</param>
    /// <param name="citations">Citations to include in the message.</param>
    /// <exception cref="StreamingException">Throws if the stream has already ended.</exception>
    public void QueueTextChunk(string text, IList<Citation>? citations = null)
    {
        if (this._ended)
        {
            throw new StreamingException("The stream has already ended.");
        }

        Message += text;

        // If there are citations, modify the content so that the sources are numbers instead of [doc1], [doc2], etc.
        this.Message = FormatCitationsResponse(this.Message);

        QueueNextChunk();
    }

    /// <summary>
    /// Ends the stream by sending the final message to the client.
    /// </summary>
    /// <returns>A Task representing the async operation</returns>
    /// <exception cref="StreamingException">Throws if the stream has already ended.</exception>
    public Task EndStream()
    {
        if (this._ended)
        {
            throw new StreamingException("The stream has already ended.");
        }

        this._ended = true;
        QueueNextChunk();

        // Wait for the queue to drain
        return WaitForQueue()!;
    }

    /// <summary>
    /// Queue an activity to be sent to the client.
    /// </summary>
    /// <param name="factory"></param>
    private void QueueActivity(Func<Activity> factory)
    {
        this._queue.Add(factory);

        // If there's no sync in progress, start one
        if (this._queueSync == null || this._queueSync.IsCompleted)
        {
            this._queueSync = DrainQueue();

            if (this._queueSync.IsFaulted)
            {
                Exception? ex = this._queueSync.Exception;
                this._queueSync = null;
                throw new StreamingException($"Error occurred when sending activity while streaming", ex!);
            }
        }
    }

    /// <summary>
    /// Queue the next chunk of text to be sent to the client.
    /// </summary>
    private void QueueNextChunk()
    {
        // Check if we are already waiting to send a chunk
        if (this._chunkQueued)
        {
            return;
        }

        // Queue a chunk of text to be sent
        this._chunkQueued = true;
        QueueActivity(() =>
        {
            this._chunkQueued = false;

            if (this._ended)
            {
                // Send final message
                Activity activity = CreateReplyActivity("message", Message, new StreamingChannelData
                {
                    StreamType = Schema.StreamType.Final,
                });

                if (Attachments != null && Attachments.Count > 0)
                {
                    activity.Attachments = Attachments;
                }
                return activity;
            }
            else
            {
                // Send typing activity
                return CreateReplyActivity("typing", Message, new StreamingChannelData
                {
                    StreamType = Schema.StreamType.Streaming,
                    StreamSequence = this._nextSequence++,
                });
            }
        });
    }

    /// <summary>
    /// Sends any queued activities to the client until the queue is empty.
    /// </summary>
    private async Task DrainQueue()
    {
        try
        {
            while (this._queue.Count > 0)
            {
                // Get next activity from queue
                Activity activity = _queue[0]();
                await SendActivity(activity).ConfigureAwait(false);
                _queue.RemoveAt(0);
            }
        }
        catch (Exception ex)
        {
            throw new StreamingException("Error draining queue", ex);
        }
    }

    /// <summary>
    /// Sends an activity to the client and saves the stream ID returned.
    /// </summary>
    /// <param name="activity">The activity to send.</param>
    /// <returns>A Task representing the async operation.</returns>
    private async Task SendActivity(Activity activity)
    {
        // Set activity ID to the assigned stream ID
        if (!string.IsNullOrEmpty(StreamId) && activity.ChannelData is StreamingChannelData channelData)
        {
            channelData.StreamId = StreamId;
            activity.ChannelData = channelData;
        }

        // Add stream info entity
        if (activity.ChannelData is StreamingChannelData streamData)
        {
            activity.Entities ??= new List<Entity>();
            
            var streamInfoEntity = new Entity("streaminfo");
            streamInfoEntity.Properties!["streamId"] = streamData.StreamId;
            streamInfoEntity.Properties["streamType"] = streamData.StreamType;
            streamInfoEntity.Properties["streamSequence"] = streamData.StreamSequence;
            
            activity.Entities.Add(streamInfoEntity);
        }

        // Add citations if present and not final
        if (this.Citations != null && this.Citations.Count > 0 && !this._ended)
        {
            List<ClientCitation>? currCitations = GetUsedCitations(this.Message, this.Citations);
            if (currCitations != null && currCitations.Count > 0)
            {
                activity.Entities ??= new List<Entity>();
                var aiEntity = new Entity("ai");
                aiEntity.Properties!["citations"] = currCitations;
                activity.Entities.Add(aiEntity);
            }
        }

        // Add in Powered by AI feature flags for final message
        if (this._ended && activity.ChannelData is StreamingChannelData finalChannelData)
        {
            if (EnableFeedbackLoop == true)
            {
                finalChannelData.FeedbackLoopEnabled = true;
                finalChannelData.FeedbackLoopType = FeedbackLoopType;
            }
            else
            {
                finalChannelData.FeedbackLoopEnabled = false;
            }

            // Add in Generated by AI label
            if (this.EnableGeneratedByAILabel == true)
            {
                activity.Entities ??= new List<Entity>();
                var aiEntity = new Entity("ai");
                
                if (this.Citations != null && this.Citations.Count > 0)
                {
                    List<ClientCitation>? currCitations = GetUsedCitations(this.Message, this.Citations);
                    if (currCitations != null && currCitations.Count > 0)
                    {
                        aiEntity.Properties!["citations"] = currCitations;
                    }
                }

                activity.Entities.Add(aiEntity);
            }
        }

        ResourceResponse response = await _botApplication.SendActivityWithResponseAsync(activity).ConfigureAwait(false);

        // Delay between updates to prevent overwhelming the Bot Framework service
        // This is configurable via the StreamingDelayMs property
        await Task.Delay(StreamingDelayMs).ConfigureAwait(false);

        // Save assigned stream ID
        if (string.IsNullOrEmpty(StreamId))
        {
            StreamId = response.Id;
        }
    }

    /// <summary>
    /// Creates a reply activity based on the incoming activity
    /// </summary>
    private Activity CreateReplyActivity(string type, string? text, StreamingChannelData channelData)
    {
        return new Activity
        {
            Type = type,
            Text = text,
            ChannelId = _incomingActivity.ChannelId,
            ServiceUrl = _incomingActivity.ServiceUrl,
            Conversation = _incomingActivity.Conversation,
            From = _incomingActivity.Recipient,
            Recipient = _incomingActivity.From,
            ReplyToId = _incomingActivity.Id,
            ChannelData = channelData
        };
    }

    /// <summary>
    /// Creates a snippet from content with a maximum length
    /// </summary>
    private static string Snippet(string? content, int maxLength)
    {
        if (string.IsNullOrEmpty(content))
        {
            return string.Empty;
        }

        if (content.Length <= maxLength)
        {
            return content;
        }

        return string.Concat(content.AsSpan(0, maxLength), "...");
    }

    /// <summary>
    /// Formats citation references in the message
    /// </summary>
    private static string FormatCitationsResponse(string message)
    {
        // Replace [doc1], [doc2], etc. with [1], [2], etc.
        return Regex.Replace(message, @"\[doc(\d+)\]", "[$1]");
    }

    /// <summary>
    /// Gets the citations that are actually used in the message
    /// </summary>
    private static List<ClientCitation>? GetUsedCitations(string message, List<ClientCitation> citations)
    {
        if (citations == null || citations.Count == 0)
        {
            return null;
        }

        var usedCitations = new List<ClientCitation>();
        foreach (var citation in citations)
        {
            // Check if the citation position is referenced in the message
            if (message.Contains($"[{citation.Position}]"))
            {
                usedCitations.Add(citation);
            }
        }

        return usedCitations.Count > 0 ? usedCitations : null;
    }
}
